apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: greeter-service
  namespace: greeter
  labels:
    app: greeter-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-service
  template:
    metadata:
      labels:
        app: greeter-service
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: greeter-service
        image: public.ecr.aws/f8u4w2p3/rust/greeter:latest
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"